apiVersion: v1
kind: ConfigMap
metadata:
  name: itverse-config
  namespace: itverse
data:
  DB_HOST: "itverse-rds.cu5um4sqcrw1.us-east-1.rds.amazonaws.com"
  DB_PORT: "3306"
  DB_NAME: "lms_db"
  DB_USER: "itverse"
